export const LOAD_POSTS = 'post/LOAD_POSTS';
export const SET_POSTS = 'post/SET_POSTS';

export const REMOVE_POST_START = 'post/REMOVE_POST_START';
export const REMOVE_POST_SUCCESS = 'post/REMOVE_POST_SUCCESS';

export const LOAD_CURRENT_POST = 'post/LOAD_CURRENT_POST';
export const SET_CURRENT_POST = 'post/SET_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'post/CLEAR_CURRENT_POST';

export const SET_READ_LIST_POST = 'readlist/SET_READ_LIST_POST';
export const DELETE_READ_LIST_POST = 'readlist/DELETE_READ_LIST_POST';

export const SET_FILTER_POSTS = 'readlist/SET_FILTER_POSTS';

export const UPDATE_CURRENT_POST_START = 'updatePopup/UPDATE_CURRENT_POST_START';
export const UPDATE_CURRENT_POST_SUCCESS = 'updatePopup/UPDATE_CURRENT_POST_SUCCESS';

export const CREATE_CURRENT_POST_START = 'updatePopup/CREATE_CURRENT_POST_START';
export const CREATE_CURRENT_POST_SUCCESS = 'updatePopup/CREATE_CURRENT_POST_SUCCESS';

export const SET_FILTER_SEARCH_POST = 'search/SET_FILTER_SEARCH_POST';
export const LOAD_SEARCH_POST_START = 'search/LOAD_SEARCH_POST_START';
export const SET_SEARCH_POST_SUCCESS = 'search/SET_SEARCH_POST_SUCCESS';

export const SET_FILTER_SEARCH_POST_SELECT = 'search/SET_FILTER_SEARCH_POST_SELECT';
export const LOAD_SEARCH_POST_START_SELECT = 'search/LOAD_SEARCH_POST_START_SELECT';
export const SET_SEARCH_POST_SUCCESS_SELECT = 'search/SET_SEARCH_POST_SUCCESS_SELECT';
export const CLEAN_SEARCH_POST_SELECT = 'search/CLEAN_SEARCH_POST_SELECT';
